In [5]:
import numpy as np

def gaussElimin(a,b):
    n = len(b)

    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a [i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam * a[k,k+1:n]
                b[i] = b[i] - lam*b[k]

    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]

    return b
    

In [13]:
A = np.array([[2.0, 3.0, 1.0],[4.0, 7.0, 5.0], [6.0, 18.0, 6.0]])
B = np.array([1.0, 2.0, 5.0])

print(A)
print('\n')
print(B)
print('\n')

#Calling gaussElimin function...
gaussElimin(A,B)

[[ 2.  3.  1.]
 [ 4.  7.  5.]
 [ 6. 18.  6.]]


[1. 2. 5.]




array([ 0.16666667,  0.25      , -0.08333333])

In [ ]:
Given System :
  
2x+3y+z=1(Eq1)
4x+7y+5z=2(Eq2)
6x+18y+6z=5(Eq3)

Step 1: Write the Augmented Matrix

[ 2 3  1 | 1]
[ 4 7  5 | 2]
[ 6 18 6 | 5]

Step 2: Eliminate entries below the pivot in column 1
We want to eliminate the x terms from row 2 and row 3.

R2 = R2 - 2×R1
R2=[4,7,5,2]−2×[2,3,1,1]=[0,1,3,0]

R3 = R3 - 3×R1
R3=[6,18,6,5]−3×[2,3,1,1]=[0,9,3,2]

New matrix :
[ 2 3 1 | 1]
[ 0 1 3 | 0]
[ 0 9 3 | 2]

Step 3: Eliminate entry below the pivot in column 2

R3 = R3 - 9×R2
R3=[0,9,3,2]−9×[0,1,3,0]=[0,0,−24,2]

Now we find the upper triangular matrix
[ 2 3  1  | 1]
[ 0 1  3  | 0]
[ 0 0 -24 | 1]

From row 3:
    −24z=2⇒z= 2/-24 = -1/12

From row 2:
    y+3z=0⇒y+3(-1/12) = 0
    or y = 1/4

From row 1:
    x = 1/6

Final Answer:

x = 1/6 , y = 1/4 , z = -1/12
